---
apiVersion: v1
kind: Service
metadata:
  namespace: kevincr
  name: simple-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    simple-app: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kevincr
  name: simple-app
spec:
  selector:
    matchLabels:
      simple-app: ""
  template:
    metadata:
      labels:
        simple-app: ""
    spec:
      containers:
      - name: simple-app
        # uncomment the following line if you want to pull the original image from docker
        # image: docker.io/dkalinin/k8s-simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
        # uncomment the next line if you are pulling from registry.lab.livefire.dev
        # image: registry.lab.livefire.dev/kevincr/simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
        # uncomment the next line if you are pulling from harbor.lab.livefire.dev
        # image: harbor.lab.livefire.dev/kevincr/simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
        # uncomment the next line if you are pulling from harbor.dev.livefire.lab
        # image: harbor.dev.livefire.lab/kevincr/simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
        # the following line is specifically to support the class delivery
        image: harbor.dev.livefire.lab/<put_your_username_here>/simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
        env:
        - name: HELLO_MSG
          value: stranger
